/* Generated By:JJTree: Do not edit this line. ASTaroundArea.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTaroundArea extends SimpleNode {
  public ASTaroundArea(int id) {
    super(id);
  }

  public ASTaroundArea(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ef4889db568d828a82966b65a3c00f15 (do not edit this line) */
