/* Generated By:JJTree: Do not edit this line. ASTAreaName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTAreaName extends SimpleNode {
  public String areaName;


public ASTAreaName(int id) {
    super(id);
  }

  public ASTAreaName(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=40b087913f8b43b00e3bf7ec9b4ebf91 (do not edit this line) */
