/* Generated By:JJTree: Do not edit this line. ASTCompnayName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCompnayName extends SimpleNode {
  public ASTCompnayName(int id) {
    super(id);
  }

  public ASTCompnayName(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=53678d23a91e5f6a8c1e7bb46c5098b8 (do not edit this line) */
