/* Generated By:JJTree: Do not edit this line. ASTCompanyNameOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCompanyNameOr extends SimpleNode {
  public ASTCompanyNameOr(int id) {
    super(id);
  }

  public ASTCompanyNameOr(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3e4a0cc8b5e4138ab2157ba3c0412e60 (do not edit this line) */
