/* Generated By:JJTree: Do not edit this line. ASTCompnayType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCompnayType extends SimpleNode {
  public String companyType;


public ASTCompnayType(int id) {
    super(id);
  }

  public ASTCompnayType(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b8617e18484fab3b5904c80d01fe8834 (do not edit this line) */
