/* Generated By:JJTree: Do not edit this line. ASTCompanyName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCompanyName extends SimpleNode {
  public String companyName;


public ASTCompanyName(int id) {
    super(id);
  }

  public ASTCompanyName(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c9d9ef92b2e94cbdf01c22d10bcfa7e9 (do not edit this line) */
