/* Generated By:JJTree: Do not edit this line. ASTCompanyTypeOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCompanyTypeOr extends SimpleNode {
  public ASTCompanyTypeOr(int id) {
    super(id);
  }

  public ASTCompanyTypeOr(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=74e22650121ed84da0781868cbabdb75 (do not edit this line) */
