/* Generated By:JJTree: Do not edit this line. ASTpreferableArea.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTpreferableArea extends SimpleNode {
  public ASTpreferableArea(int id) {
    super(id);
  }

  public ASTpreferableArea(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1667d77cc456645d279f7f71ecf1119a (do not edit this line) */
