/* Generated By:JJTree: Do not edit this line. ASTpreferableCompany.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTpreferableCompany extends SimpleNode {
  public ASTpreferableCompany(int id) {
    super(id);
  }

  public ASTpreferableCompany(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eb732a4cca882d544367a95ceb9403d0 (do not edit this line) */
