/* Generated By:JJTree: Do not edit this line. ASTtitle.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTtitle extends SimpleNode {
  public String title;


public ASTtitle(int id) {
    super(id);
  }

  public ASTtitle(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6eb97c0f217d5b25dacb413b45b5cf36 (do not edit this line) */
