/* Generated By:JavaCC: Do not edit this line. QueryParserVisitor.java Version 5.0 */
package parser;

public interface QueryParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTseek node, Object data);
  public Object visit(ASTJobOr node, Object data);
  public Object visit(ASTJob node, Object data);
  public Object visit(ASTtitle node, Object data);
  public Object visit(ASTcompany node, Object data);
  public Object visit(ASTpreferableCompany node, Object data);
  public Object visit(ASTCompanyNameOr node, Object data);
  public Object visit(ASTCompanyName node, Object data);
  public Object visit(ASTCompanyTypeOr node, Object data);
  public Object visit(ASTCompnayType node, Object data);
  public Object visit(ASTarea node, Object data);
  public Object visit(ASTpreferableArea node, Object data);
  public Object visit(ASTinArea node, Object data);
  public Object visit(ASTaroundArea node, Object data);
  public Object visit(ASTAreaNameOr node, Object data);
  public Object visit(ASTAreaName node, Object data);
  public Object visit(ASTsalary node, Object data);
}
/* JavaCC - OriginalChecksum=a8196cd368d8dac6ee9ba0fbf0b3243c (do not edit this line) */
