/* Generated By:JJTree&JavaCC: Do not edit this line. QueryParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEEKING = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int A = 7;
  /** RegularExpression Id. */
  int POSITION = 8;
  /** RegularExpression Id. */
  int IN = 9;
  /** RegularExpression Id. */
  int AROUND = 10;
  /** RegularExpression Id. */
  int PREFERABLY = 11;
  /** RegularExpression Id. */
  int WITH = 12;
  /** RegularExpression Id. */
  int SALARY = 13;
  /** RegularExpression Id. */
  int OF = 14;
  /** RegularExpression Id. */
  int TITLE = 15;
  /** RegularExpression Id. */
  int COMPANYTYPE = 16;
  /** RegularExpression Id. */
  int AREANAME = 17;
  /** RegularExpression Id. */
  int UNIT = 18;
  /** RegularExpression Id. */
  int COMPANYNAME = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int SALARYAMOUNT = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"seeking\"",
    "\"or\"",
    "\"a\"",
    "\"position\"",
    "\"in\"",
    "\"around\"",
    "\"preferably\"",
    "\"with\"",
    "\"salary\"",
    "\"of\"",
    "<TITLE>",
    "<COMPANYTYPE>",
    "<AREANAME>",
    "<UNIT>",
    "<COMPANYNAME>",
    "<NUMBER>",
    "<SALARYAMOUNT>",
  };

}
