/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 5.0 */
package parser;

public interface QueryParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSEEK = 1;
  public int JJTVOID = 2;
  public int JJTJOBOR = 3;
  public int JJTJOB = 4;
  public int JJTTITLE = 5;
  public int JJTCOMPANY = 6;
  public int JJTPREFERABLECOMPANY = 7;
  public int JJTCOMPANYNAMEOR = 8;
  public int JJTCOMPANYNAME = 9;
  public int JJTCOMPANYTYPEOR = 10;
  public int JJTCOMPNAYTYPE = 11;
  public int JJTAREA = 12;
  public int JJTPREFERABLEAREA = 13;
  public int JJTINAREA = 14;
  public int JJTAROUNDAREA = 15;
  public int JJTAREANAMEOR = 16;
  public int JJTAREANAME = 17;
  public int JJTSALARY = 18;


  public String[] jjtNodeName = {
    "Start",
    "seek",
    "void",
    "JobOr",
    "Job",
    "title",
    "company",
    "preferableCompany",
    "CompanyNameOr",
    "CompanyName",
    "CompanyTypeOr",
    "CompnayType",
    "area",
    "preferableArea",
    "inArea",
    "aroundArea",
    "AreaNameOr",
    "AreaName",
    "salary",
  };
}
/* JavaCC - OriginalChecksum=87d0156d9a7536c7dcc9cd6175d282aa (do not edit this line) */
